// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: council_votes.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVotesByProposalAndVote = `-- name: CountVotesByProposalAndVote :one
SELECT COUNT(*) FROM council_votes
WHERE proposal_id = $1 AND vote = $2
`

type CountVotesByProposalAndVoteParams struct {
	ProposalID string `json:"proposal_id"`
	Vote       string `json:"vote"`
}

func (q *Queries) CountVotesByProposalAndVote(ctx context.Context, arg CountVotesByProposalAndVoteParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVotesByProposalAndVote, arg.ProposalID, arg.Vote)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCouncilVote = `-- name: CreateCouncilVote :one
INSERT INTO council_votes (id, proposal_id, voter_id, vote, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, proposal_id, voter_id, vote, created_at
`

type CreateCouncilVoteParams struct {
	ID         string             `json:"id"`
	ProposalID string             `json:"proposal_id"`
	VoterID    string             `json:"voter_id"`
	Vote       string             `json:"vote"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCouncilVote(ctx context.Context, arg CreateCouncilVoteParams) (CouncilVote, error) {
	row := q.db.QueryRow(ctx, createCouncilVote,
		arg.ID,
		arg.ProposalID,
		arg.VoterID,
		arg.Vote,
		arg.CreatedAt,
	)
	var i CouncilVote
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.VoterID,
		&i.Vote,
		&i.CreatedAt,
	)
	return i, err
}

const getVoteByProposalAndVoter = `-- name: GetVoteByProposalAndVoter :one
SELECT id, proposal_id, voter_id, vote, created_at FROM council_votes
WHERE proposal_id = $1 AND voter_id = $2
`

type GetVoteByProposalAndVoterParams struct {
	ProposalID string `json:"proposal_id"`
	VoterID    string `json:"voter_id"`
}

func (q *Queries) GetVoteByProposalAndVoter(ctx context.Context, arg GetVoteByProposalAndVoterParams) (CouncilVote, error) {
	row := q.db.QueryRow(ctx, getVoteByProposalAndVoter, arg.ProposalID, arg.VoterID)
	var i CouncilVote
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.VoterID,
		&i.Vote,
		&i.CreatedAt,
	)
	return i, err
}

const listDistinctOpenProposals = `-- name: ListDistinctOpenProposals :many
SELECT DISTINCT proposal_id FROM council_votes
ORDER BY proposal_id
`

func (q *Queries) ListDistinctOpenProposals(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctOpenProposals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var proposal_id string
		if err := rows.Scan(&proposal_id); err != nil {
			return nil, err
		}
		items = append(items, proposal_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesByProposal = `-- name: ListVotesByProposal :many
SELECT id, proposal_id, voter_id, vote, created_at FROM council_votes
WHERE proposal_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVotesByProposal(ctx context.Context, proposalID string) ([]CouncilVote, error) {
	rows, err := q.db.Query(ctx, listVotesByProposal, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CouncilVote{}
	for rows.Next() {
		var i CouncilVote
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.VoterID,
			&i.Vote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
