// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: council_votes.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCouncilVote = `-- name: CreateCouncilVote :one
INSERT INTO council_votes (id, proposal_id, voter_id, vote, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, proposal_id, voter_id, vote, created_at
`

type CreateCouncilVoteParams struct {
	ID         string             `json:"id"`
	ProposalID string             `json:"proposal_id"`
	VoterID    string             `json:"voter_id"`
	Vote       string             `json:"vote"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCouncilVote(ctx context.Context, arg CreateCouncilVoteParams) (CouncilVote, error) {
	row := q.db.QueryRow(ctx, createCouncilVote,
		arg.ID,
		arg.ProposalID,
		arg.VoterID,
		arg.Vote,
		arg.CreatedAt,
	)
	var i CouncilVote
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.VoterID,
		&i.Vote,
		&i.CreatedAt,
	)
	return i, err
}

const listVotesByProposal = `-- name: ListVotesByProposal :many

SELECT id, proposal_id, voter_id, vote, created_at FROM council_votes
WHERE proposal_id = $1
ORDER BY created_at ASC
`

// ListVotesByProposal is what every tally is computed from. Approvals,
// rejections and whether the caller has already voted all come off this one
// read, because a proposal's votes are bounded by the size of the council —
// a handful of rows. It replaced a pair of COUNT-per-side queries plus a
// targeted GetVoteByProposalAndVoter, which was three round trips to answer
// three questions about the same few rows.
//
// There is deliberately no query listing proposals out of this table any more.
// ListDistinctOpenProposals used to reconstruct the set of proposals from the
// votes cast on them, which was the only way to enumerate them while no
// proposals table existed — it could not see a proposal nobody had voted on
// yet, and it called every proposal it found "open" regardless of outcome.
// Migration 00021 gives proposals their own table; ask that.
func (q *Queries) ListVotesByProposal(ctx context.Context, proposalID string) ([]CouncilVote, error) {
	rows, err := q.db.Query(ctx, listVotesByProposal, proposalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CouncilVote{}
	for rows.Next() {
		var i CouncilVote
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.VoterID,
			&i.Vote,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
