// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_reactions.sql

package postgres

import (
	"context"
)

const batchCountReactionsByPosts = `-- name: BatchCountReactionsByPosts :many
SELECT post_id, reaction_type, COUNT(*)::int AS count
FROM reactions
WHERE post_id = ANY($1::text[])
GROUP BY post_id, reaction_type
`

type BatchCountReactionsByPostsRow struct {
	PostID       string `json:"post_id"`
	ReactionType string `json:"reaction_type"`
	Count        int32  `json:"count"`
}

// Counts reactions grouped by post_id and reaction_type for a batch of posts.
func (q *Queries) BatchCountReactionsByPosts(ctx context.Context, postIds []string) ([]BatchCountReactionsByPostsRow, error) {
	rows, err := q.db.Query(ctx, batchCountReactionsByPosts, postIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchCountReactionsByPostsRow{}
	for rows.Next() {
		var i BatchCountReactionsByPostsRow
		if err := rows.Scan(&i.PostID, &i.ReactionType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchGetUserReactionsForPosts = `-- name: BatchGetUserReactionsForPosts :many
SELECT post_id, reaction_type
FROM reactions
WHERE user_id = $1 AND post_id = ANY($2::text[])
`

type BatchGetUserReactionsForPostsParams struct {
	UserID  string   `json:"user_id"`
	PostIds []string `json:"post_ids"`
}

type BatchGetUserReactionsForPostsRow struct {
	PostID       string `json:"post_id"`
	ReactionType string `json:"reaction_type"`
}

// Returns the current user's reactions for a batch of posts.
func (q *Queries) BatchGetUserReactionsForPosts(ctx context.Context, arg BatchGetUserReactionsForPostsParams) ([]BatchGetUserReactionsForPostsRow, error) {
	rows, err := q.db.Query(ctx, batchGetUserReactionsForPosts, arg.UserID, arg.PostIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchGetUserReactionsForPostsRow{}
	for rows.Next() {
		var i BatchGetUserReactionsForPostsRow
		if err := rows.Scan(&i.PostID, &i.ReactionType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
