// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET consumed_at = $2, consumed_by = $3
WHERE id = $1
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > $2
RETURNING id, token_hash, email, note, inviter_id, created_at, expires_at, consumed_at, consumed_by, revoked_at
`

type ConsumeInviteParams struct {
	ID         string             `json:"id"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ConsumedBy pgtype.Text        `json:"consumed_by"`
}

// Redemption, exactly once.
//
// The liveness clause is repeated here rather than trusted from the read that
// selected this row, and that repetition is the whole guard: two concurrent
// sign-ins with the same address both find the invitation live, both arrive
// here, and only one updates a row. The loser gets no rows back and creates no
// vouch, so an invitation can never produce two endorsements.
func (q *Queries) ConsumeInvite(ctx context.Context, arg ConsumeInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, arg.ID, arg.ConsumedAt, arg.ConsumedBy)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.Note,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.RevokedAt,
	)
	return i, err
}

const countConsumedInvitesByEmail = `-- name: CountConsumedInvitesByEmail :one
SELECT COUNT(*) FROM invites
WHERE lower(email) = lower($1::text) AND consumed_at IS NOT NULL
`

// Whether this address has already been through the door. See
// InviteService.Create for why an accepted invitation refuses a new one and why
// this app-side check is where the duplicate-account question stops.
func (q *Queries) CountConsumedInvitesByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countConsumedInvitesByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvitesByInviterSince = `-- name: CountInvitesByInviterSince :one
SELECT COUNT(*) FROM invites
WHERE inviter_id = $1 AND created_at >= $2
`

type CountInvitesByInviterSinceParams struct {
	InviterID string             `json:"inviter_id"`
	Since     pgtype.Timestamptz `json:"since"`
}

// Half of the combined daily budget; CountVouchesByVoucherSince is the other.
// Revoked invitations are counted on purpose: the point of the budget is to
// limit how many endorsements one member can put into the world in a day, and
// inviting-then-revoking in a loop must not be a way to buy more.
func (q *Queries) CountInvitesByInviterSince(ctx context.Context, arg CountInvitesByInviterSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitesByInviterSince, arg.InviterID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (id, token_hash, email, note, inviter_id, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, token_hash, email, note, inviter_id, created_at, expires_at, consumed_at, consumed_by, revoked_at
`

type CreateInviteParams struct {
	ID        string             `json:"id"`
	TokenHash string             `json:"token_hash"`
	Email     string             `json:"email"`
	Note      string             `json:"note"`
	InviterID string             `json:"inviter_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.TokenHash,
		arg.Email,
		arg.Note,
		arg.InviterID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.Note,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.RevokedAt,
	)
	return i, err
}

const getBlockingInviteByEmail = `-- name: GetBlockingInviteByEmail :one
SELECT id, token_hash, email, note, inviter_id, created_at, expires_at, consumed_at, consumed_by, revoked_at FROM invites
WHERE lower(email) = lower($1::text)
  AND consumed_at IS NULL
  AND revoked_at IS NULL
`

// The row idx_invites_live_email would collide with: unconsumed and unrevoked,
// whether or not it has expired.
//
// This is deliberately NOT the liveness clause above. The unique index cannot
// test expiry — an index predicate has to be immutable — so an expired
// invitation still occupies the address as far as the constraint is concerned.
// Create reads this row to tell the two cases apart: a live one refuses the
// request, an expired one is reaped and replaced.
func (q *Queries) GetBlockingInviteByEmail(ctx context.Context, email string) (Invite, error) {
	row := q.db.QueryRow(ctx, getBlockingInviteByEmail, email)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.Note,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.RevokedAt,
	)
	return i, err
}

const getLiveInviteByEmail = `-- name: GetLiveInviteByEmail :one
SELECT i.id, i.token_hash, i.email, i.note, i.inviter_id, i.created_at, i.expires_at, i.consumed_at, i.consumed_by, i.revoked_at, inviter.display_name AS inviter_display_name
FROM invites i
JOIN users inviter ON inviter.id = i.inviter_id
WHERE lower(i.email) = lower($1::text)
  AND i.consumed_at IS NULL
  AND i.revoked_at IS NULL
  AND i.expires_at > $2
`

type GetLiveInviteByEmailParams struct {
	Email string             `json:"email"`
	Now   pgtype.Timestamptz `json:"now"`
}

type GetLiveInviteByEmailRow struct {
	Invite             Invite `json:"invite"`
	InviterDisplayName string `json:"inviter_display_name"`
}

// The redemption path's read: the invitation waiting for whoever just signed in
// with this address. Same liveness clause as the token lookup.
func (q *Queries) GetLiveInviteByEmail(ctx context.Context, arg GetLiveInviteByEmailParams) (GetLiveInviteByEmailRow, error) {
	row := q.db.QueryRow(ctx, getLiveInviteByEmail, arg.Email, arg.Now)
	var i GetLiveInviteByEmailRow
	err := row.Scan(
		&i.Invite.ID,
		&i.Invite.TokenHash,
		&i.Invite.Email,
		&i.Invite.Note,
		&i.Invite.InviterID,
		&i.Invite.CreatedAt,
		&i.Invite.ExpiresAt,
		&i.Invite.ConsumedAt,
		&i.Invite.ConsumedBy,
		&i.Invite.RevokedAt,
		&i.InviterDisplayName,
	)
	return i, err
}

const getLiveInviteByTokenHash = `-- name: GetLiveInviteByTokenHash :one
SELECT i.id, i.token_hash, i.email, i.note, i.inviter_id, i.created_at, i.expires_at, i.consumed_at, i.consumed_by, i.revoked_at, inviter.display_name AS inviter_display_name
FROM invites i
JOIN users inviter ON inviter.id = i.inviter_id
WHERE i.token_hash = $1
  AND i.consumed_at IS NULL
  AND i.revoked_at IS NULL
  AND i.expires_at > $2
`

type GetLiveInviteByTokenHashParams struct {
	TokenHash string             `json:"token_hash"`
	Now       pgtype.Timestamptz `json:"now"`
}

type GetLiveInviteByTokenHashRow struct {
	Invite             Invite `json:"invite"`
	InviterDisplayName string `json:"inviter_display_name"`
}

// The registration gate's and the public lookup's only read.
//
// "Live" is spelled out here rather than derived in Go so that an invitation
// that has been consumed, revoked or has simply run out is indistinguishable
// from one that never existed: every caller of this query answers a miss with
// the same 404, and a query that returned the row and let the service judge it
// would make that uniformity one forgotten branch away from an oracle.
func (q *Queries) GetLiveInviteByTokenHash(ctx context.Context, arg GetLiveInviteByTokenHashParams) (GetLiveInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getLiveInviteByTokenHash, arg.TokenHash, arg.Now)
	var i GetLiveInviteByTokenHashRow
	err := row.Scan(
		&i.Invite.ID,
		&i.Invite.TokenHash,
		&i.Invite.Email,
		&i.Invite.Note,
		&i.Invite.InviterID,
		&i.Invite.CreatedAt,
		&i.Invite.ExpiresAt,
		&i.Invite.ConsumedAt,
		&i.Invite.ConsumedBy,
		&i.Invite.RevokedAt,
		&i.InviterDisplayName,
	)
	return i, err
}

const listInvitesByInviter = `-- name: ListInvitesByInviter :many
SELECT i.id, i.token_hash, i.email, i.note, i.inviter_id, i.created_at, i.expires_at, i.consumed_at, i.consumed_by, i.revoked_at, consumer.display_name AS consumed_by_display_name
FROM invites i
LEFT JOIN users consumer ON consumer.id = i.consumed_by
WHERE i.inviter_id = $1
ORDER BY i.created_at DESC
`

type ListInvitesByInviterRow struct {
	Invite                Invite      `json:"invite"`
	ConsumedByDisplayName pgtype.Text `json:"consumed_by_display_name"`
}

// The caller's own invitations, newest first.
//
// consumed_by is joined by name because the list is read by a person: "accepted
// by Dana" is the whole reason the row is interesting, and the id renders as
// unreadable UUID. A LEFT JOIN because consumed_by is null on every invitation
// that has not been accepted, which is most of them.
//
// token_hash is selected — this is SELECT i.* — and the repository drops it
// before the row leaves the persistence layer. domain.Invite has nowhere to put
// it.
func (q *Queries) ListInvitesByInviter(ctx context.Context, inviterID string) ([]ListInvitesByInviterRow, error) {
	rows, err := q.db.Query(ctx, listInvitesByInviter, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitesByInviterRow{}
	for rows.Next() {
		var i ListInvitesByInviterRow
		if err := rows.Scan(
			&i.Invite.ID,
			&i.Invite.TokenHash,
			&i.Invite.Email,
			&i.Invite.Note,
			&i.Invite.InviterID,
			&i.Invite.CreatedAt,
			&i.Invite.ExpiresAt,
			&i.Invite.ConsumedAt,
			&i.Invite.ConsumedBy,
			&i.Invite.RevokedAt,
			&i.ConsumedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reapInviteForReuse = `-- name: ReapInviteForReuse :exec
UPDATE invites
SET revoked_at = $2
WHERE id = $1 AND consumed_at IS NULL AND revoked_at IS NULL
`

type ReapInviteForReuseParams struct {
	ID        string             `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

// Frees an address held by an expired invitation, so a fresh one can be sent.
//
// Unqualified by expiry on purpose: Create has already established that this
// row is past its expires_at, and re-testing it here against a second clock
// reading would open a window where neither statement thinks it is responsible.
// The consumed/revoked guards stay, so a row that was accepted or withdrawn in
// the meantime is left exactly as it is and the INSERT that follows loses to
// the unique index instead — which is the right answer, because in that case
// the address is legitimately taken.
func (q *Queries) ReapInviteForReuse(ctx context.Context, arg ReapInviteForReuseParams) error {
	_, err := q.db.Exec(ctx, reapInviteForReuse, arg.ID, arg.RevokedAt)
	return err
}

const revokeInviteByInviter = `-- name: RevokeInviteByInviter :one
UPDATE invites
SET revoked_at = $2
WHERE id = $1
  AND inviter_id = $3
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > $4
RETURNING id, token_hash, email, note, inviter_id, created_at, expires_at, consumed_at, consumed_by, revoked_at
`

type RevokeInviteByInviterParams struct {
	ID        string             `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	InviterID string             `json:"inviter_id"`
	Now       pgtype.Timestamptz `json:"now"`
}

// Withdrawing an invitation you sent, and only one that is still open.
//
// Both the ownership test and the liveness clause are in the WHERE rather than
// checked in Go against a row read first. Zero rows is then the single answer
// to "not yours", "already accepted", "already revoked" and "no such
// invitation", which is exactly the uniformity the handler needs to 404 without
// telling a caller whether somebody else's invitation exists.
func (q *Queries) RevokeInviteByInviter(ctx context.Context, arg RevokeInviteByInviterParams) (Invite, error) {
	row := q.db.QueryRow(ctx, revokeInviteByInviter,
		arg.ID,
		arg.RevokedAt,
		arg.InviterID,
		arg.Now,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.Note,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConsumedBy,
		&i.RevokedAt,
	)
	return i, err
}
