// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation_reliefs.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModerationRelief = `-- name: CreateModerationRelief :one
INSERT INTO moderation_reliefs (id, target_user_id, moderator_id, relief_type, previous_expires_at, was_in_force, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, target_user_id, moderator_id, relief_type, previous_expires_at, was_in_force, created_at
`

type CreateModerationReliefParams struct {
	ID                string             `json:"id"`
	TargetUserID      string             `json:"target_user_id"`
	ModeratorID       string             `json:"moderator_id"`
	ReliefType        string             `json:"relief_type"`
	PreviousExpiresAt pgtype.Timestamptz `json:"previous_expires_at"`
	WasInForce        bool               `json:"was_in_force"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateModerationRelief(ctx context.Context, arg CreateModerationReliefParams) (ModerationRelief, error) {
	row := q.db.QueryRow(ctx, createModerationRelief,
		arg.ID,
		arg.TargetUserID,
		arg.ModeratorID,
		arg.ReliefType,
		arg.PreviousExpiresAt,
		arg.WasInForce,
		arg.CreatedAt,
	)
	var i ModerationRelief
	err := row.Scan(
		&i.ID,
		&i.TargetUserID,
		&i.ModeratorID,
		&i.ReliefType,
		&i.PreviousExpiresAt,
		&i.WasInForce,
		&i.CreatedAt,
	)
	return i, err
}

const listMuteLiftsInForceByTarget = `-- name: ListMuteLiftsInForceByTarget :many
SELECT id, target_user_id, moderator_id, relief_type, previous_expires_at, was_in_force, created_at FROM moderation_reliefs
WHERE target_user_id = $1
  AND relief_type = 'mute_lift'
  AND was_in_force = TRUE
ORDER BY created_at DESC
LIMIT $2
`

type ListMuteLiftsInForceByTargetParams struct {
	TargetUserID string `json:"target_user_id"`
	Limit        int32  `json:"limit"`
}

// The member's own view of being released. was_in_force is filtered here rather
// than after the read: the lift endpoint is idempotent and accepts a lift
// against anyone, so filtering in Go after LIMIT would let a run of no-op lifts
// push the release that actually freed somebody out of the window.
func (q *Queries) ListMuteLiftsInForceByTarget(ctx context.Context, arg ListMuteLiftsInForceByTargetParams) ([]ModerationRelief, error) {
	rows, err := q.db.Query(ctx, listMuteLiftsInForceByTarget, arg.TargetUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationRelief{}
	for rows.Next() {
		var i ModerationRelief
		if err := rows.Scan(
			&i.ID,
			&i.TargetUserID,
			&i.ModeratorID,
			&i.ReliefType,
			&i.PreviousExpiresAt,
			&i.WasInForce,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
