// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation_actions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModerationAction = `-- name: CreateModerationAction :one
INSERT INTO moderation_actions (id, target_user_id, moderator_id, action_type, severity, reason, duration_seconds, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, target_user_id, moderator_id, action_type, severity, reason, duration_seconds, created_at, expires_at
`

type CreateModerationActionParams struct {
	ID              string             `json:"id"`
	TargetUserID    string             `json:"target_user_id"`
	ModeratorID     string             `json:"moderator_id"`
	ActionType      string             `json:"action_type"`
	Severity        int32              `json:"severity"`
	Reason          string             `json:"reason"`
	DurationSeconds pgtype.Int8        `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) (ModerationAction, error) {
	row := q.db.QueryRow(ctx, createModerationAction,
		arg.ID,
		arg.TargetUserID,
		arg.ModeratorID,
		arg.ActionType,
		arg.Severity,
		arg.Reason,
		arg.DurationSeconds,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.TargetUserID,
		&i.ModeratorID,
		&i.ActionType,
		&i.Severity,
		&i.Reason,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listModerationActionsByModerator = `-- name: ListModerationActionsByModerator :many
SELECT m.id, m.target_user_id, m.moderator_id, m.action_type, m.severity, m.reason, m.duration_seconds, m.created_at, m.expires_at,
       target.display_name AS target_display_name,
       moderator.display_name AS moderator_display_name
FROM moderation_actions m
JOIN users target ON target.id = m.target_user_id
JOIN users moderator ON moderator.id = m.moderator_id
WHERE m.moderator_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListModerationActionsByModeratorParams struct {
	ModeratorID string `json:"moderator_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListModerationActionsByModeratorRow struct {
	ModerationAction     ModerationAction `json:"moderation_action"`
	TargetDisplayName    string           `json:"target_display_name"`
	ModeratorDisplayName string           `json:"moderator_display_name"`
}

// The other direction of the same trail, joined the same way.
func (q *Queries) ListModerationActionsByModerator(ctx context.Context, arg ListModerationActionsByModeratorParams) ([]ListModerationActionsByModeratorRow, error) {
	rows, err := q.db.Query(ctx, listModerationActionsByModerator, arg.ModeratorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModerationActionsByModeratorRow{}
	for rows.Next() {
		var i ListModerationActionsByModeratorRow
		if err := rows.Scan(
			&i.ModerationAction.ID,
			&i.ModerationAction.TargetUserID,
			&i.ModerationAction.ModeratorID,
			&i.ModerationAction.ActionType,
			&i.ModerationAction.Severity,
			&i.ModerationAction.Reason,
			&i.ModerationAction.DurationSeconds,
			&i.ModerationAction.CreatedAt,
			&i.ModerationAction.ExpiresAt,
			&i.TargetDisplayName,
			&i.ModeratorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerationActionsByTarget = `-- name: ListModerationActionsByTarget :many
SELECT m.id, m.target_user_id, m.moderator_id, m.action_type, m.severity, m.reason, m.duration_seconds, m.created_at, m.expires_at,
       target.display_name AS target_display_name,
       moderator.display_name AS moderator_display_name
FROM moderation_actions m
JOIN users target ON target.id = m.target_user_id
JOIN users moderator ON moderator.id = m.moderator_id
WHERE m.target_user_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListModerationActionsByTargetParams struct {
	TargetUserID string `json:"target_user_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

type ListModerationActionsByTargetRow struct {
	ModerationAction     ModerationAction `json:"moderation_action"`
	TargetDisplayName    string           `json:"target_display_name"`
	ModeratorDisplayName string           `json:"moderator_display_name"`
}

// Both parties are joined by name. The audit trail names who was acted on and
// who acted, and a moderator reading it should not have to look either id up by
// hand. Both columns are NOT NULL references to users, so neither join can drop
// an action. Note this is the audit trail's own view: which moderator handled a
// case stays behind the council check in the handler, exactly as it did when
// only the id was carried.
func (q *Queries) ListModerationActionsByTarget(ctx context.Context, arg ListModerationActionsByTargetParams) ([]ListModerationActionsByTargetRow, error) {
	rows, err := q.db.Query(ctx, listModerationActionsByTarget, arg.TargetUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModerationActionsByTargetRow{}
	for rows.Next() {
		var i ListModerationActionsByTargetRow
		if err := rows.Scan(
			&i.ModerationAction.ID,
			&i.ModerationAction.TargetUserID,
			&i.ModerationAction.ModeratorID,
			&i.ModerationAction.ActionType,
			&i.ModerationAction.Severity,
			&i.ModerationAction.Reason,
			&i.ModerationAction.DurationSeconds,
			&i.ModerationAction.CreatedAt,
			&i.ModerationAction.ExpiresAt,
			&i.TargetDisplayName,
			&i.ModeratorDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
