// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation_actions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModerationAction = `-- name: CreateModerationAction :one
INSERT INTO moderation_actions (id, target_user_id, moderator_id, action_type, severity, reason, duration_seconds, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, target_user_id, moderator_id, action_type, severity, reason, duration_seconds, created_at, expires_at
`

type CreateModerationActionParams struct {
	ID              string             `json:"id"`
	TargetUserID    string             `json:"target_user_id"`
	ModeratorID     string             `json:"moderator_id"`
	ActionType      string             `json:"action_type"`
	Severity        int32              `json:"severity"`
	Reason          string             `json:"reason"`
	DurationSeconds pgtype.Int8        `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateModerationAction(ctx context.Context, arg CreateModerationActionParams) (ModerationAction, error) {
	row := q.db.QueryRow(ctx, createModerationAction,
		arg.ID,
		arg.TargetUserID,
		arg.ModeratorID,
		arg.ActionType,
		arg.Severity,
		arg.Reason,
		arg.DurationSeconds,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.TargetUserID,
		&i.ModeratorID,
		&i.ActionType,
		&i.Severity,
		&i.Reason,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getModerationActionByID = `-- name: GetModerationActionByID :one
SELECT id, target_user_id, moderator_id, action_type, severity, reason, duration_seconds, created_at, expires_at FROM moderation_actions WHERE id = $1
`

func (q *Queries) GetModerationActionByID(ctx context.Context, id string) (ModerationAction, error) {
	row := q.db.QueryRow(ctx, getModerationActionByID, id)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.TargetUserID,
		&i.ModeratorID,
		&i.ActionType,
		&i.Severity,
		&i.Reason,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listModerationActionsByModerator = `-- name: ListModerationActionsByModerator :many
SELECT id, target_user_id, moderator_id, action_type, severity, reason, duration_seconds, created_at, expires_at FROM moderation_actions
WHERE moderator_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListModerationActionsByModeratorParams struct {
	ModeratorID string `json:"moderator_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListModerationActionsByModerator(ctx context.Context, arg ListModerationActionsByModeratorParams) ([]ModerationAction, error) {
	rows, err := q.db.Query(ctx, listModerationActionsByModerator, arg.ModeratorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationAction{}
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.TargetUserID,
			&i.ModeratorID,
			&i.ActionType,
			&i.Severity,
			&i.Reason,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerationActionsByTarget = `-- name: ListModerationActionsByTarget :many
SELECT id, target_user_id, moderator_id, action_type, severity, reason, duration_seconds, created_at, expires_at FROM moderation_actions
WHERE target_user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListModerationActionsByTargetParams struct {
	TargetUserID string `json:"target_user_id"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) ListModerationActionsByTarget(ctx context.Context, arg ListModerationActionsByTargetParams) ([]ModerationAction, error) {
	rows, err := q.db.Query(ctx, listModerationActionsByTarget, arg.TargetUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModerationAction{}
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.TargetUserID,
			&i.ModeratorID,
			&i.ActionType,
			&i.Severity,
			&i.Reason,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
