// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ModerationAction struct {
	ID              string             `json:"id"`
	TargetUserID    string             `json:"target_user_id"`
	ModeratorID     string             `json:"moderator_id"`
	ActionType      string             `json:"action_type"`
	Severity        int32              `json:"severity"`
	Reason          string             `json:"reason"`
	DurationSeconds pgtype.Int8        `json:"duration_seconds"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type Post struct {
	ID            string             `json:"id"`
	AuthorID      string             `json:"author_id"`
	Body          string             `json:"body"`
	ImagePath     string             `json:"image_path"`
	Status        string             `json:"status"`
	RemovalReason string             `json:"removal_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	EditedAt      pgtype.Timestamptz `json:"edited_at"`
}

type Reaction struct {
	ID           string             `json:"id"`
	UserID       string             `json:"user_id"`
	PostID       string             `json:"post_id"`
	ReactionType string             `json:"reaction_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Report struct {
	ID         string             `json:"id"`
	ReporterID string             `json:"reporter_id"`
	PostID     string             `json:"post_id"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TrustPenalty struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	ModerationActionID string             `json:"moderation_action_id"`
	PenaltyAmount      float64            `json:"penalty_amount"`
	HopDepth           int32              `json:"hop_depth"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	DecaysAt           pgtype.Timestamptz `json:"decays_at"`
}

type User struct {
	ID               string             `json:"id"`
	KratosIdentityID string             `json:"kratos_identity_id"`
	DisplayName      string             `json:"display_name"`
	Bio              string             `json:"bio"`
	AvatarUrl        string             `json:"avatar_url"`
	TrustScore       float64            `json:"trust_score"`
	Role             string             `json:"role"`
	IsActive         bool               `json:"is_active"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Vouch struct {
	ID        string             `json:"id"`
	VoucherID string             `json:"voucher_id"`
	VoucheeID string             `json:"vouchee_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}
