// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, author_id, body, image_path, status, removal_reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, author_id, body, image_path, status, removal_reason, created_at, edited_at
`

type CreatePostParams struct {
	ID            string             `json:"id"`
	AuthorID      string             `json:"author_id"`
	Body          string             `json:"body"`
	ImagePath     string             `json:"image_path"`
	Status        string             `json:"status"`
	RemovalReason string             `json:"removal_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.Body,
		arg.ImagePath,
		arg.Status,
		arg.RemovalReason,
		arg.CreatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.ImagePath,
		&i.Status,
		&i.RemovalReason,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, body, image_path, status, removal_reason, created_at, edited_at FROM posts WHERE id = $1
`

func (q *Queries) GetPostByID(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.ImagePath,
		&i.Status,
		&i.RemovalReason,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT id, author_id, body, image_path, status, removal_reason, created_at, edited_at FROM posts WHERE author_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListPostsByAuthorParams struct {
	AuthorID string `json:"author_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor, arg.AuthorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Body,
			&i.ImagePath,
			&i.Status,
			&i.RemovalReason,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsFeed = `-- name: ListPostsFeed :many
SELECT id, author_id, body, image_path, status, removal_reason, created_at, edited_at FROM posts
WHERE status = 'visible' AND id < $1
ORDER BY id DESC
LIMIT $2
`

type ListPostsFeedParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListPostsFeed(ctx context.Context, arg ListPostsFeedParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsFeed, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Body,
			&i.ImagePath,
			&i.Status,
			&i.RemovalReason,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsFeedFirst = `-- name: ListPostsFeedFirst :many
SELECT id, author_id, body, image_path, status, removal_reason, created_at, edited_at FROM posts
WHERE status = 'visible'
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListPostsFeedFirst(ctx context.Context, limit int32) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsFeedFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Body,
			&i.ImagePath,
			&i.Status,
			&i.RemovalReason,
			&i.CreatedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts SET status = $2, removal_reason = $3 WHERE id = $1
`

type SoftDeletePostParams struct {
	ID            string `json:"id"`
	Status        string `json:"status"`
	RemovalReason string `json:"removal_reason"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.Exec(ctx, softDeletePost, arg.ID, arg.Status, arg.RemovalReason)
	return err
}

const updatePostBody = `-- name: UpdatePostBody :one
UPDATE posts SET body = $2, edited_at = NOW() WHERE id = $1
RETURNING id, author_id, body, image_path, status, removal_reason, created_at, edited_at
`

type UpdatePostBodyParams struct {
	ID   string `json:"id"`
	Body string `json:"body"`
}

func (q *Queries) UpdatePostBody(ctx context.Context, arg UpdatePostBodyParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePostBody, arg.ID, arg.Body)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.ImagePath,
		&i.Status,
		&i.RemovalReason,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}
