// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPostsByAuthorSince = `-- name: CountPostsByAuthorSince :one
SELECT COUNT(*) FROM posts
WHERE author_id = $1 AND created_at >= $2 AND status = 'visible'
`

type CountPostsByAuthorSinceParams struct {
	AuthorID  string             `json:"author_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountPostsByAuthorSince(ctx context.Context, arg CountPostsByAuthorSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsByAuthorSince, arg.AuthorID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsToday = `-- name: CountPostsToday :one
SELECT COUNT(*) FROM posts
WHERE created_at >= CURRENT_DATE AND status = 'visible'
`

func (q *Queries) CountPostsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPostsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, author_id, body, image_path, status, removal_reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, author_id, body, image_path, status, removal_reason, created_at, edited_at
`

type CreatePostParams struct {
	ID            string             `json:"id"`
	AuthorID      string             `json:"author_id"`
	Body          string             `json:"body"`
	ImagePath     string             `json:"image_path"`
	Status        string             `json:"status"`
	RemovalReason string             `json:"removal_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.Body,
		arg.ImagePath,
		arg.Status,
		arg.RemovalReason,
		arg.CreatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Body,
		&i.ImagePath,
		&i.Status,
		&i.RemovalReason,
		&i.CreatedAt,
		&i.EditedAt,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT p.id, p.author_id, p.body, p.image_path, p.status, p.removal_reason, p.created_at, p.edited_at,
       u.display_name AS author_display_name, u.avatar_url AS author_avatar_url
FROM posts p
JOIN users u ON p.author_id = u.id
WHERE p.id = $1
`

type GetPostByIDRow struct {
	Post              Post   `json:"post"`
	AuthorDisplayName string `json:"author_display_name"`
	AuthorAvatarUrl   string `json:"author_avatar_url"`
}

func (q *Queries) GetPostByID(ctx context.Context, id string) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Body,
		&i.Post.ImagePath,
		&i.Post.Status,
		&i.Post.RemovalReason,
		&i.Post.CreatedAt,
		&i.Post.EditedAt,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
	)
	return i, err
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT p.id, p.author_id, p.body, p.image_path, p.status, p.removal_reason, p.created_at, p.edited_at,
       u.display_name AS author_display_name, u.avatar_url AS author_avatar_url
FROM posts p
JOIN users u ON p.author_id = u.id
WHERE p.author_id = $1 AND p.status = 'visible'
ORDER BY p.created_at DESC
LIMIT $2
`

type ListPostsByAuthorParams struct {
	AuthorID string `json:"author_id"`
	Limit    int32  `json:"limit"`
}

type ListPostsByAuthorRow struct {
	Post              Post   `json:"post"`
	AuthorDisplayName string `json:"author_display_name"`
	AuthorAvatarUrl   string `json:"author_avatar_url"`
}

// Removed posts are excluded here for the same reason they are excluded from
// the feed: a profile is a public listing, and a moderator-removed post carries
// removal_reason, which is a moderator's private note.
func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]ListPostsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor, arg.AuthorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsByAuthorRow{}
	for rows.Next() {
		var i ListPostsByAuthorRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.AuthorID,
			&i.Post.Body,
			&i.Post.ImagePath,
			&i.Post.Status,
			&i.Post.RemovalReason,
			&i.Post.CreatedAt,
			&i.Post.EditedAt,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsFeed = `-- name: ListPostsFeed :many
SELECT p.id, p.author_id, p.body, p.image_path, p.status, p.removal_reason, p.created_at, p.edited_at,
       u.display_name AS author_display_name, u.avatar_url AS author_avatar_url
FROM posts p
JOIN users u ON p.author_id = u.id
WHERE p.status = 'visible' AND p.id < $1
ORDER BY p.id DESC
LIMIT $2
`

type ListPostsFeedParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

type ListPostsFeedRow struct {
	Post              Post   `json:"post"`
	AuthorDisplayName string `json:"author_display_name"`
	AuthorAvatarUrl   string `json:"author_avatar_url"`
}

func (q *Queries) ListPostsFeed(ctx context.Context, arg ListPostsFeedParams) ([]ListPostsFeedRow, error) {
	rows, err := q.db.Query(ctx, listPostsFeed, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsFeedRow{}
	for rows.Next() {
		var i ListPostsFeedRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.AuthorID,
			&i.Post.Body,
			&i.Post.ImagePath,
			&i.Post.Status,
			&i.Post.RemovalReason,
			&i.Post.CreatedAt,
			&i.Post.EditedAt,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsFeedFirst = `-- name: ListPostsFeedFirst :many
SELECT p.id, p.author_id, p.body, p.image_path, p.status, p.removal_reason, p.created_at, p.edited_at,
       u.display_name AS author_display_name, u.avatar_url AS author_avatar_url
FROM posts p
JOIN users u ON p.author_id = u.id
WHERE p.status = 'visible'
ORDER BY p.id DESC
LIMIT $1
`

type ListPostsFeedFirstRow struct {
	Post              Post   `json:"post"`
	AuthorDisplayName string `json:"author_display_name"`
	AuthorAvatarUrl   string `json:"author_avatar_url"`
}

func (q *Queries) ListPostsFeedFirst(ctx context.Context, limit int32) ([]ListPostsFeedFirstRow, error) {
	rows, err := q.db.Query(ctx, listPostsFeedFirst, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPostsFeedFirstRow{}
	for rows.Next() {
		var i ListPostsFeedFirstRow
		if err := rows.Scan(
			&i.Post.ID,
			&i.Post.AuthorID,
			&i.Post.Body,
			&i.Post.ImagePath,
			&i.Post.Status,
			&i.Post.RemovalReason,
			&i.Post.CreatedAt,
			&i.Post.EditedAt,
			&i.AuthorDisplayName,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts SET status = $2, removal_reason = $3 WHERE id = $1
`

type SoftDeletePostParams struct {
	ID            string `json:"id"`
	Status        string `json:"status"`
	RemovalReason string `json:"removal_reason"`
}

func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.Exec(ctx, softDeletePost, arg.ID, arg.Status, arg.RemovalReason)
	return err
}

const updatePostBody = `-- name: UpdatePostBody :one
UPDATE posts p SET body = $2, edited_at = NOW()
FROM users u
WHERE p.id = $1 AND u.id = p.author_id
RETURNING p.id, p.author_id, p.body, p.image_path, p.status, p.removal_reason, p.created_at, p.edited_at,
          u.display_name AS author_display_name, u.avatar_url AS author_avatar_url
`

type UpdatePostBodyParams struct {
	ID   string `json:"id"`
	Body string `json:"body"`
}

type UpdatePostBodyRow struct {
	Post              Post   `json:"post"`
	AuthorDisplayName string `json:"author_display_name"`
	AuthorAvatarUrl   string `json:"author_avatar_url"`
}

// The updated row is joined back to users so that the post returned by an edit
// carries the same author fields as every read path. Without it the edit
// response alone would come back with a blank author name.
func (q *Queries) UpdatePostBody(ctx context.Context, arg UpdatePostBodyParams) (UpdatePostBodyRow, error) {
	row := q.db.QueryRow(ctx, updatePostBody, arg.ID, arg.Body)
	var i UpdatePostBodyRow
	err := row.Scan(
		&i.Post.ID,
		&i.Post.AuthorID,
		&i.Post.Body,
		&i.Post.ImagePath,
		&i.Post.Status,
		&i.Post.RemovalReason,
		&i.Post.CreatedAt,
		&i.Post.EditedAt,
		&i.AuthorDisplayName,
		&i.AuthorAvatarUrl,
	)
	return i, err
}
