// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: proposals.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProposal = `-- name: CreateProposal :one
INSERT INTO proposals (id, type, target_user_id, rationale, created_by, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, target_user_id, rationale, created_by, status, created_at, decided_at
`

type CreateProposalParams struct {
	ID           string             `json:"id"`
	Type         string             `json:"type"`
	TargetUserID pgtype.Text        `json:"target_user_id"`
	Rationale    string             `json:"rationale"`
	CreatedBy    string             `json:"created_by"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProposal(ctx context.Context, arg CreateProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, createProposal,
		arg.ID,
		arg.Type,
		arg.TargetUserID,
		arg.Rationale,
		arg.CreatedBy,
		arg.Status,
		arg.CreatedAt,
	)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetUserID,
		&i.Rationale,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideProposal = `-- name: DecideProposal :one
UPDATE proposals
SET status = $2, decided_at = $3
WHERE id = $1 AND status = 'open'
RETURNING id, type, target_user_id, rationale, created_by, status, created_at, decided_at
`

type DecideProposalParams struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	DecidedAt pgtype.Timestamptz `json:"decided_at"`
}

// Flips a proposal out of 'open' and stamps when. The status guard in the WHERE
// clause makes this a no-op on an already-decided proposal rather than a second
// decision overwriting the first, and returning no row is how the caller learns
// somebody else decided it first.
func (q *Queries) DecideProposal(ctx context.Context, arg DecideProposalParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, decideProposal, arg.ID, arg.Status, arg.DecidedAt)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetUserID,
		&i.Rationale,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const findOpenProposalByTypeAndTarget = `-- name: FindOpenProposalByTypeAndTarget :one
SELECT id, type, target_user_id, rationale, created_by, status, created_at, decided_at FROM proposals
WHERE type = $1
  AND COALESCE(target_user_id, '') = COALESCE($2::text, '')
  AND status = 'open'
`

type FindOpenProposalByTypeAndTargetParams struct {
	Type         string      `json:"type"`
	TargetUserID pgtype.Text `json:"target_user_id"`
}

// The readable half of the partial unique index in 00021. The index is what
// actually guarantees one open proposal per (type, target); this exists so the
// council is told "there is already an open motion about this" instead of
// receiving a constraint violation.
//
// COALESCE on both sides so the bootstrap_reentry case — target NULL — matches
// itself, which `target_user_id = $2` would not: NULL = NULL is unknown.
func (q *Queries) FindOpenProposalByTypeAndTarget(ctx context.Context, arg FindOpenProposalByTypeAndTargetParams) (Proposal, error) {
	row := q.db.QueryRow(ctx, findOpenProposalByTypeAndTarget, arg.Type, arg.TargetUserID)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetUserID,
		&i.Rationale,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getProposal = `-- name: GetProposal :one
SELECT id, type, target_user_id, rationale, created_by, status, created_at, decided_at FROM proposals WHERE id = $1
`

func (q *Queries) GetProposal(ctx context.Context, id string) (Proposal, error) {
	row := q.db.QueryRow(ctx, getProposal, id)
	var i Proposal
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TargetUserID,
		&i.Rationale,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listDecidedProposals = `-- name: ListDecidedProposals :many
SELECT p.id, p.type, p.target_user_id, p.rationale, p.created_by, p.status, p.created_at, p.decided_at,
       COALESCE(t.display_name, '')::text AS target_display_name,
       COALESCE(c.display_name, '')::text AS created_by_display_name
FROM proposals p
LEFT JOIN users t ON t.id = p.target_user_id
LEFT JOIN users c ON c.id = p.created_by
WHERE p.status <> 'open'
ORDER BY p.decided_at DESC NULLS LAST, p.created_at DESC
LIMIT $1::int
`

type ListDecidedProposalsRow struct {
	Proposal             Proposal `json:"proposal"`
	TargetDisplayName    string   `json:"target_display_name"`
	CreatedByDisplayName string   `json:"created_by_display_name"`
}

// Newest decision first, and bounded: this is the council's record of what it
// has settled, not an archive to be paged through, so the API asks for a page
// rather than the whole history of the town.
func (q *Queries) ListDecidedProposals(ctx context.Context, rowLimit int32) ([]ListDecidedProposalsRow, error) {
	rows, err := q.db.Query(ctx, listDecidedProposals, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDecidedProposalsRow{}
	for rows.Next() {
		var i ListDecidedProposalsRow
		if err := rows.Scan(
			&i.Proposal.ID,
			&i.Proposal.Type,
			&i.Proposal.TargetUserID,
			&i.Proposal.Rationale,
			&i.Proposal.CreatedBy,
			&i.Proposal.Status,
			&i.Proposal.CreatedAt,
			&i.Proposal.DecidedAt,
			&i.TargetDisplayName,
			&i.CreatedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenProposals = `-- name: ListOpenProposals :many

SELECT p.id, p.type, p.target_user_id, p.rationale, p.created_by, p.status, p.created_at, p.decided_at,
       COALESCE(t.display_name, '')::text AS target_display_name,
       COALESCE(c.display_name, '')::text AS created_by_display_name
FROM proposals p
LEFT JOIN users t ON t.id = p.target_user_id
LEFT JOIN users c ON c.id = p.created_by
WHERE p.status = 'open'
ORDER BY p.created_at DESC
`

type ListOpenProposalsRow struct {
	Proposal             Proposal `json:"proposal"`
	TargetDisplayName    string   `json:"target_display_name"`
	CreatedByDisplayName string   `json:"created_by_display_name"`
}

// Both listings join the target and the proposer to their display names.
//
// A LEFT JOIN for the target because bootstrap_reentry has none, and a LEFT
// JOIN for the proposer too even though created_by is NOT NULL: an INNER JOIN
// there would make a proposal vanish from the council's queue if the row it
// points at ever became unreadable, and a motion disappearing is a worse
// failure than one attributed to a blank name. Both names come back as the
// empty string when absent, matching the vouch and directory listings, so a
// client falls back to the id for anything falsy.
func (q *Queries) ListOpenProposals(ctx context.Context) ([]ListOpenProposalsRow, error) {
	rows, err := q.db.Query(ctx, listOpenProposals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenProposalsRow{}
	for rows.Next() {
		var i ListOpenProposalsRow
		if err := rows.Scan(
			&i.Proposal.ID,
			&i.Proposal.Type,
			&i.Proposal.TargetUserID,
			&i.Proposal.Rationale,
			&i.Proposal.CreatedBy,
			&i.Proposal.Status,
			&i.Proposal.CreatedAt,
			&i.Proposal.DecidedAt,
			&i.TargetDisplayName,
			&i.CreatedByDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
