// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReportsByReporterSince = `-- name: CountReportsByReporterSince :one
SELECT COUNT(*) FROM reports
WHERE reporter_id = $1 AND created_at >= $2
`

type CountReportsByReporterSinceParams struct {
	ReporterID string             `json:"reporter_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountReportsByReporterSince(ctx context.Context, arg CountReportsByReporterSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByReporterSince, arg.ReporterID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (id, reporter_id, post_id, reason, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, reporter_id, post_id, reason, status, created_at
`

type CreateReportParams struct {
	ID         string             `json:"id"`
	ReporterID string             `json:"reporter_id"`
	PostID     string             `json:"post_id"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ID,
		arg.ReporterID,
		arg.PostID,
		arg.Reason,
		arg.Status,
		arg.CreatedAt,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.PostID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, reporter_id, post_id, reason, status, created_at FROM reports WHERE id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.PostID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getReportByReporterAndPost = `-- name: GetReportByReporterAndPost :one
SELECT id, reporter_id, post_id, reason, status, created_at FROM reports WHERE reporter_id = $1 AND post_id = $2
`

type GetReportByReporterAndPostParams struct {
	ReporterID string `json:"reporter_id"`
	PostID     string `json:"post_id"`
}

func (q *Queries) GetReportByReporterAndPost(ctx context.Context, arg GetReportByReporterAndPostParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByReporterAndPost, arg.ReporterID, arg.PostID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.PostID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingReports = `-- name: ListPendingReports :many
SELECT id, reporter_id, post_id, reason, status, created_at FROM reports
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListPendingReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingReports(ctx context.Context, arg ListPendingReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listPendingReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.PostID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET status = $2
WHERE id = $1
RETURNING id, reporter_id, post_id, reason, status, created_at
`

type UpdateReportStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.PostID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
