// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_history.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoleHistoryEntry = `-- name: CreateRoleHistoryEntry :one
INSERT INTO role_history (id, user_id, old_role, new_role, reason, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, old_role, new_role, reason, created_at
`

type CreateRoleHistoryEntryParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	OldRole   string             `json:"old_role"`
	NewRole   string             `json:"new_role"`
	Reason    string             `json:"reason"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateRoleHistoryEntry(ctx context.Context, arg CreateRoleHistoryEntryParams) (RoleHistory, error) {
	row := q.db.QueryRow(ctx, createRoleHistoryEntry,
		arg.ID,
		arg.UserID,
		arg.OldRole,
		arg.NewRole,
		arg.Reason,
		arg.CreatedAt,
	)
	var i RoleHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OldRole,
		&i.NewRole,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listRoleHistoryByUser = `-- name: ListRoleHistoryByUser :many
SELECT id, user_id, old_role, new_role, reason, created_at FROM role_history
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRoleHistoryByUser(ctx context.Context, userID string) ([]RoleHistory, error) {
	rows, err := q.db.Query(ctx, listRoleHistoryByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleHistory{}
	for rows.Next() {
		var i RoleHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OldRole,
			&i.NewRole,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
