// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: town_config_list.sql

package postgres

import (
	"context"
)

const listTownConfig = `-- name: ListTownConfig :many
SELECT key, value FROM town_config
`

func (q *Queries) ListTownConfig(ctx context.Context) ([]TownConfig, error) {
	rows, err := q.db.Query(ctx, listTownConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TownConfig{}
	for rows.Next() {
		var i TownConfig
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
