// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: town_config.sql

package postgres

import (
	"context"
)

const getTownConfig = `-- name: GetTownConfig :one
SELECT value FROM town_config WHERE key = $1
`

func (q *Queries) GetTownConfig(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getTownConfig, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setTownConfig = `-- name: SetTownConfig :exec
INSERT INTO town_config (key, value) VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
`

type SetTownConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetTownConfig(ctx context.Context, arg SetTownConfigParams) error {
	_, err := q.db.Exec(ctx, setTownConfig, arg.Key, arg.Value)
	return err
}
