// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trust_penalties.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrustPenalty = `-- name: CreateTrustPenalty :one
INSERT INTO trust_penalties (id, user_id, moderation_action_id, penalty_amount, hop_depth, created_at, decays_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, moderation_action_id, penalty_amount, hop_depth, created_at, decays_at
`

type CreateTrustPenaltyParams struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"user_id"`
	ModerationActionID string             `json:"moderation_action_id"`
	PenaltyAmount      float64            `json:"penalty_amount"`
	HopDepth           int32              `json:"hop_depth"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	DecaysAt           pgtype.Timestamptz `json:"decays_at"`
}

func (q *Queries) CreateTrustPenalty(ctx context.Context, arg CreateTrustPenaltyParams) (TrustPenalty, error) {
	row := q.db.QueryRow(ctx, createTrustPenalty,
		arg.ID,
		arg.UserID,
		arg.ModerationActionID,
		arg.PenaltyAmount,
		arg.HopDepth,
		arg.CreatedAt,
		arg.DecaysAt,
	)
	var i TrustPenalty
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ModerationActionID,
		&i.PenaltyAmount,
		&i.HopDepth,
		&i.CreatedAt,
		&i.DecaysAt,
	)
	return i, err
}

const listActivePenaltiesByUser = `-- name: ListActivePenaltiesByUser :many
SELECT id, user_id, moderation_action_id, penalty_amount, hop_depth, created_at, decays_at FROM trust_penalties
WHERE user_id = $1 AND (decays_at IS NULL OR decays_at > NOW())
`

func (q *Queries) ListActivePenaltiesByUser(ctx context.Context, userID string) ([]TrustPenalty, error) {
	rows, err := q.db.Query(ctx, listActivePenaltiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustPenalty{}
	for rows.Next() {
		var i TrustPenalty
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModerationActionID,
			&i.PenaltyAmount,
			&i.HopDepth,
			&i.CreatedAt,
			&i.DecaysAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustPenaltiesByActionID = `-- name: ListTrustPenaltiesByActionID :many
SELECT id, user_id, moderation_action_id, penalty_amount, hop_depth, created_at, decays_at FROM trust_penalties
WHERE moderation_action_id = $1
ORDER BY hop_depth ASC
`

func (q *Queries) ListTrustPenaltiesByActionID(ctx context.Context, moderationActionID string) ([]TrustPenalty, error) {
	rows, err := q.db.Query(ctx, listTrustPenaltiesByActionID, moderationActionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrustPenalty{}
	for rows.Next() {
		var i TrustPenalty
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ModerationActionID,
			&i.PenaltyAmount,
			&i.HopDepth,
			&i.CreatedAt,
			&i.DecaysAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
