// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserTrustBelowSince = `-- name: ClearUserTrustBelowSince :exec
UPDATE users SET trust_below_since = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) ClearUserTrustBelowSince(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearUserTrustBelowSince, id)
	return err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT COUNT(*) FROM users
WHERE is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCouncilMembers = `-- name: CountCouncilMembers :one
SELECT COUNT(*) FROM users
WHERE role = 'council' AND is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
`

func (q *Queries) CountCouncilMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCouncilMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDirectoryUsers = `-- name: CountDirectoryUsers :one
SELECT COUNT(*) FROM users
WHERE is_active = TRUE AND role <> 'banned'
  AND (suspended_until IS NULL OR suspended_until <= NOW())
  AND ($1::text = '' OR display_name ILIKE '%' || $1::text || '%')
`

// The same population as ListDirectoryUsers, so the two filters must stay
// identical: a total that disagrees with the rows is a pager that offers a page
// which comes back empty.
func (q *Queries) CountDirectoryUsers(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countDirectoryUsers, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModerators = `-- name: CountModerators :one
SELECT COUNT(*) FROM users
WHERE role = 'moderator' AND is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
`

func (q *Queries) CountModerators(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countModerators)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingUsers = `-- name: CountPendingUsers :one
SELECT COUNT(*) FROM users
WHERE role = 'pending' AND is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
`

func (q *Queries) CountPendingUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingUsersMatching = `-- name: CountPendingUsersMatching :one
SELECT COUNT(*) FROM users
WHERE role = 'pending' AND is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
  AND ($1::text = '' OR display_name ILIKE '%' || $1::text || '%')
`

// The same population as ListPendingUsersPage, so the two filters must stay
// identical: a total that disagrees with the rows is a pager offering a page
// that comes back empty. With an empty @query it counts exactly what
// CountPendingUsers counts, which is what keeps the queue's total and the
// dashboard's pending stat from contradicting each other.
func (q *Queries) CountPendingUsersMatching(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingUsersMatching, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByMinRole = `-- name: CountUsersByMinRole :one
SELECT COUNT(*) FROM users
WHERE role IN ('member', 'moderator', 'council') AND is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
`

func (q *Queries) CountUsersByMinRole(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByMinRole)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at
`

type CreateUserParams struct {
	ID               string             `json:"id"`
	KratosIdentityID string             `json:"kratos_identity_id"`
	DisplayName      string             `json:"display_name"`
	Bio              string             `json:"bio"`
	AvatarUrl        string             `json:"avatar_url"`
	TrustScore       float64            `json:"trust_score"`
	Role             string             `json:"role"`
	IsActive         bool               `json:"is_active"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.KratosIdentityID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.TrustScore,
		arg.Role,
		arg.IsActive,
		arg.JoinedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustBelowSince,
		&i.MutedUntil,
		&i.SuspendedUntil,
		&i.ResidencyClaim,
		&i.ResidencyClaimUpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

// Takes an account out of service indefinitely. Suspension no longer uses this:
// nothing sets is_active back to TRUE, which is what made every timed
// suspension permanent. Use SetUserSuspendedUntil for anything that ends.
func (q *Queries) DeactivateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at FROM users WHERE id = $1
`

// Every query below that asks for the active users means "active and not
// currently serving a suspension". A suspension is a value with an expiry
// (suspended_until) rather than a flag, so the clock is part of the question:
// `is_active = TRUE` alone would count a suspended member among the members,
// and dropping the pair would leave one still counted a day after their
// suspension lapsed. Postgres NOW() is the authority, matching
// domain.User.IsSuspended on the read side.
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustBelowSince,
		&i.MutedUntil,
		&i.SuspendedUntil,
		&i.ResidencyClaim,
		&i.ResidencyClaimUpdatedAt,
	)
	return i, err
}

const getUserByKratosID = `-- name: GetUserByKratosID :one
SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at FROM users WHERE kratos_identity_id = $1
`

func (q *Queries) GetUserByKratosID(ctx context.Context, kratosIdentityID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKratosID, kratosIdentityID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustBelowSince,
		&i.MutedUntil,
		&i.SuspendedUntil,
		&i.ResidencyClaim,
		&i.ResidencyClaimUpdatedAt,
	)
	return i, err
}

const listActiveNonBannedUsers = `-- name: ListActiveNonBannedUsers :many
SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at FROM users
WHERE is_active = TRUE AND role NOT IN ('pending', 'banned')
  AND (suspended_until IS NULL OR suspended_until <= NOW())
ORDER BY created_at
`

func (q *Queries) ListActiveNonBannedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveNonBannedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.KratosIdentityID,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.TrustScore,
			&i.Role,
			&i.IsActive,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrustBelowSince,
			&i.MutedUntil,
			&i.SuspendedUntil,
			&i.ResidencyClaim,
			&i.ResidencyClaimUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDirectoryUsers = `-- name: ListDirectoryUsers :many

SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at FROM users
WHERE is_active = TRUE AND role <> 'banned'
  AND (suspended_until IS NULL OR suspended_until <= NOW())
  AND ($1::text = '' OR display_name ILIKE '%' || $1::text || '%')
ORDER BY joined_at DESC, id DESC
LIMIT $3::int OFFSET $2::int
`

type ListDirectoryUsersParams struct {
	Query     string `json:"query"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

// The member directory. Pending users cannot post, so before this existed they
// were invisible to everyone who might vouch for them — the vouch graph had no
// way to start. It therefore includes pending accounts deliberately: being
// findable is the whole point.
//
// Banned and deactivated accounts are excluded, as is anyone currently serving
// a suspension, on the same clock as every other query in this file. An empty
// @query matches everyone; otherwise it is a case-insensitive substring of the
// display name. The caller escapes LIKE's own metacharacters before it gets
// here, so a resident searching for "_" finds an underscore rather than every
// neighbour.
//
// Newest first, because the residents most likely to need a vouch are the ones
// who just arrived. id breaks ties: joined_at can repeat, and two rows in an
// ambiguous order would shuffle between pages of an offset-paginated listing.
func (q *Queries) ListDirectoryUsers(ctx context.Context, arg ListDirectoryUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listDirectoryUsers, arg.Query, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.KratosIdentityID,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.TrustScore,
			&i.Role,
			&i.IsActive,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrustBelowSince,
			&i.MutedUntil,
			&i.SuspendedUntil,
			&i.ResidencyClaim,
			&i.ResidencyClaimUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingUsers = `-- name: ListPendingUsers :many
SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at FROM users
WHERE role = 'pending' AND is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
ORDER BY created_at ASC
`

func (q *Queries) ListPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.KratosIdentityID,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.TrustScore,
			&i.Role,
			&i.IsActive,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrustBelowSince,
			&i.MutedUntil,
			&i.SuspendedUntil,
			&i.ResidencyClaim,
			&i.ResidencyClaimUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingUsersPage = `-- name: ListPendingUsersPage :many

SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at FROM users
WHERE role = 'pending' AND is_active = TRUE
  AND (suspended_until IS NULL OR suspended_until <= NOW())
  AND ($1::text = '' OR display_name ILIKE '%' || $1::text || '%')
ORDER BY joined_at ASC, id ASC
LIMIT $3::int OFFSET $2::int
`

type ListPendingUsersPageParams struct {
	Query     string `json:"query"`
	RowOffset int32  `json:"row_offset"`
	RowLimit  int32  `json:"row_limit"`
}

// The council's approval queue, one page at a time. ListPendingUsers above is
// the whole roster and stays: the display-name backfill walks every applicant
// and has no page to be on.
//
// Oldest first, which is the fair order for a queue: the applicant who has been
// waiting longest is the one the council sees first, and a registration flood
// cannot bury somebody who signed up last week behind fifty newer strangers.
// It is the opposite of the member directory, which is newest-first because it
// answers a different question — who has just arrived and needs a vouch.
//
// joined_at rather than created_at, which the unpaged listing sorts on, because
// joined_at is the date the queue shows next to each name: an order the council
// cannot verify against what is on screen invites a bug report every time the
// two columns drift. id breaks ties, so paging with an offset cannot repeat or
// skip an applicant when two accounts share a timestamp.
//
// An empty @query matches everyone; otherwise it is a case-insensitive
// substring of the display name, escaped by the caller exactly as the directory
// escapes it.
func (q *Queries) ListPendingUsersPage(ctx context.Context, arg ListPendingUsersPageParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listPendingUsersPage, arg.Query, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.KratosIdentityID,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.TrustScore,
			&i.Role,
			&i.IsActive,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrustBelowSince,
			&i.MutedUntil,
			&i.SuspendedUntil,
			&i.ResidencyClaim,
			&i.ResidencyClaimUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserMutedUntil = `-- name: SetUserMutedUntil :exec
UPDATE users SET muted_until = $2, updated_at = NOW() WHERE id = $1
`

type SetUserMutedUntilParams struct {
	ID         string             `json:"id"`
	MutedUntil pgtype.Timestamptz `json:"muted_until"`
}

// Passing NULL lifts the mute. Setting it always overwrites rather than
// extending, so a moderator issuing a shorter mute over a longer one gets the
// length they chose.
func (q *Queries) SetUserMutedUntil(ctx context.Context, arg SetUserMutedUntilParams) error {
	_, err := q.db.Exec(ctx, setUserMutedUntil, arg.ID, arg.MutedUntil)
	return err
}

const setUserResidencyClaim = `-- name: SetUserResidencyClaim :exec
UPDATE users
SET residency_claim            = $2,
    residency_claim_updated_at = NOW(),
    updated_at                 = NOW()
WHERE id = $1
`

type SetUserResidencyClaimParams struct {
	ID             string `json:"id"`
	ResidencyClaim string `json:"residency_claim"`
}

// The resident's own statement of where they live, for the council's approval
// queue. Writing the empty string clears it.
//
// residency_claim_updated_at is stamped on every write including a clear, so
// "withdrew their claim last week" stays distinguishable from "never made one",
// which is the whole reason the column is nullable while the claim is not.
func (q *Queries) SetUserResidencyClaim(ctx context.Context, arg SetUserResidencyClaimParams) error {
	_, err := q.db.Exec(ctx, setUserResidencyClaim, arg.ID, arg.ResidencyClaim)
	return err
}

const setUserSuspendedUntil = `-- name: SetUserSuspendedUntil :exec
UPDATE users SET suspended_until = $2, updated_at = NOW() WHERE id = $1
`

type SetUserSuspendedUntilParams struct {
	ID             string             `json:"id"`
	SuspendedUntil pgtype.Timestamptz `json:"suspended_until"`
}

// The same contract as SetUserMutedUntil one severity up: NULL lifts the
// suspension, and a new one overwrites rather than extends.
func (q *Queries) SetUserSuspendedUntil(ctx context.Context, arg SetUserSuspendedUntilParams) error {
	_, err := q.db.Exec(ctx, setUserSuspendedUntil, arg.ID, arg.SuspendedUntil)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2, bio = $3, avatar_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at, trust_below_since, muted_until, suspended_until, residency_claim, residency_claim_updated_at
`

type UpdateUserProfileParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	Bio         string `json:"bio"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrustBelowSince,
		&i.MutedUntil,
		&i.SuspendedUntil,
		&i.ResidencyClaim,
		&i.ResidencyClaimUpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserTrustBelowSince = `-- name: UpdateUserTrustBelowSince :exec
UPDATE users SET trust_below_since = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserTrustBelowSinceParams struct {
	ID              string             `json:"id"`
	TrustBelowSince pgtype.Timestamptz `json:"trust_below_since"`
}

func (q *Queries) UpdateUserTrustBelowSince(ctx context.Context, arg UpdateUserTrustBelowSinceParams) error {
	_, err := q.db.Exec(ctx, updateUserTrustBelowSince, arg.ID, arg.TrustBelowSince)
	return err
}

const updateUserTrustScore = `-- name: UpdateUserTrustScore :exec
UPDATE users SET trust_score = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserTrustScoreParams struct {
	ID         string  `json:"id"`
	TrustScore float64 `json:"trust_score"`
}

func (q *Queries) UpdateUserTrustScore(ctx context.Context, arg UpdateUserTrustScoreParams) error {
	_, err := q.db.Exec(ctx, updateUserTrustScore, arg.ID, arg.TrustScore)
	return err
}
