// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersByMinRole = `-- name: CountUsersByMinRole :one
SELECT COUNT(*) FROM users
WHERE role IN ('member', 'moderator', 'council') AND is_active = TRUE
`

func (q *Queries) CountUsersByMinRole(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByMinRole)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at
`

type CreateUserParams struct {
	ID               string             `json:"id"`
	KratosIdentityID string             `json:"kratos_identity_id"`
	DisplayName      string             `json:"display_name"`
	Bio              string             `json:"bio"`
	AvatarUrl        string             `json:"avatar_url"`
	TrustScore       float64            `json:"trust_score"`
	Role             string             `json:"role"`
	IsActive         bool               `json:"is_active"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.KratosIdentityID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.TrustScore,
		arg.Role,
		arg.IsActive,
		arg.JoinedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByKratosID = `-- name: GetUserByKratosID :one
SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at FROM users WHERE kratos_identity_id = $1
`

func (q *Queries) GetUserByKratosID(ctx context.Context, kratosIdentityID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKratosID, kratosIdentityID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingUsers = `-- name: ListPendingUsers :many
SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at FROM users
WHERE role = 'pending' AND is_active = TRUE
ORDER BY created_at ASC
`

func (q *Queries) ListPendingUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listPendingUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.KratosIdentityID,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.TrustScore,
			&i.Role,
			&i.IsActive,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at FROM users WHERE role = $1 ORDER BY created_at DESC LIMIT $2
`

type ListUsersByRoleParams struct {
	Role  string `json:"role"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, arg.Role, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.KratosIdentityID,
			&i.DisplayName,
			&i.Bio,
			&i.AvatarUrl,
			&i.TrustScore,
			&i.Role,
			&i.IsActive,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $2, bio = $3, avatar_url = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, kratos_identity_id, display_name, bio, avatar_url, trust_score, role, is_active, joined_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
	Bio         string `json:"bio"`
	AvatarUrl   string `json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.KratosIdentityID,
		&i.DisplayName,
		&i.Bio,
		&i.AvatarUrl,
		&i.TrustScore,
		&i.Role,
		&i.IsActive,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   string `json:"id"`
	Role string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserTrustScore = `-- name: UpdateUserTrustScore :exec
UPDATE users SET trust_score = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserTrustScoreParams struct {
	ID         string  `json:"id"`
	TrustScore float64 `json:"trust_score"`
}

func (q *Queries) UpdateUserTrustScore(ctx context.Context, arg UpdateUserTrustScoreParams) error {
	_, err := q.db.Exec(ctx, updateUserTrustScore, arg.ID, arg.TrustScore)
	return err
}
