// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vouches.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVouchesByVoucherSince = `-- name: CountVouchesByVoucherSince :one
SELECT COUNT(*) FROM vouches
WHERE voucher_id = $1 AND created_at >= $2
`

type CountVouchesByVoucherSinceParams struct {
	VoucherID string             `json:"voucher_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountVouchesByVoucherSince(ctx context.Context, arg CountVouchesByVoucherSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVouchesByVoucherSince, arg.VoucherID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVouch = `-- name: CreateVouch :one
INSERT INTO vouches (id, voucher_id, vouchee_id, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, voucher_id, vouchee_id, status, created_at, revoked_at
`

type CreateVouchParams struct {
	ID        string             `json:"id"`
	VoucherID string             `json:"voucher_id"`
	VoucheeID string             `json:"vouchee_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateVouch(ctx context.Context, arg CreateVouchParams) (Vouch, error) {
	row := q.db.QueryRow(ctx, createVouch,
		arg.ID,
		arg.VoucherID,
		arg.VoucheeID,
		arg.Status,
		arg.CreatedAt,
	)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getVouchByID = `-- name: GetVouchByID :one
SELECT id, voucher_id, vouchee_id, status, created_at, revoked_at FROM vouches WHERE id = $1
`

func (q *Queries) GetVouchByID(ctx context.Context, id string) (Vouch, error) {
	row := q.db.QueryRow(ctx, getVouchByID, id)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getVouchByPair = `-- name: GetVouchByPair :one
SELECT id, voucher_id, vouchee_id, status, created_at, revoked_at FROM vouches WHERE voucher_id = $1 AND vouchee_id = $2
`

type GetVouchByPairParams struct {
	VoucherID string `json:"voucher_id"`
	VoucheeID string `json:"vouchee_id"`
}

func (q *Queries) GetVouchByPair(ctx context.Context, arg GetVouchByPairParams) (Vouch, error) {
	row := q.db.QueryRow(ctx, getVouchByPair, arg.VoucherID, arg.VoucheeID)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveVouchesByVouchee = `-- name: ListActiveVouchesByVouchee :many
SELECT id, voucher_id, vouchee_id, status, created_at, revoked_at FROM vouches
WHERE vouchee_id = $1 AND status = 'active'
ORDER BY created_at
`

func (q *Queries) ListActiveVouchesByVouchee(ctx context.Context, voucheeID string) ([]Vouch, error) {
	rows, err := q.db.Query(ctx, listActiveVouchesByVouchee, voucheeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vouch{}
	for rows.Next() {
		var i Vouch
		if err := rows.Scan(
			&i.ID,
			&i.VoucherID,
			&i.VoucheeID,
			&i.Status,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVouchesByVoucher = `-- name: ListActiveVouchesByVoucher :many
SELECT id, voucher_id, vouchee_id, status, created_at, revoked_at FROM vouches
WHERE voucher_id = $1 AND status = 'active'
ORDER BY created_at
`

func (q *Queries) ListActiveVouchesByVoucher(ctx context.Context, voucherID string) ([]Vouch, error) {
	rows, err := q.db.Query(ctx, listActiveVouchesByVoucher, voucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vouch{}
	for rows.Next() {
		var i Vouch
		if err := rows.Scan(
			&i.ID,
			&i.VoucherID,
			&i.VoucheeID,
			&i.Status,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeVouch = `-- name: RevokeVouch :one
UPDATE vouches
SET status = 'revoked', revoked_at = NOW()
WHERE id = $1 AND status = 'active'
RETURNING id, voucher_id, vouchee_id, status, created_at, revoked_at
`

func (q *Queries) RevokeVouch(ctx context.Context, id string) (Vouch, error) {
	row := q.db.QueryRow(ctx, revokeVouch, id)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
