// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vouches.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveModeratorVouchesForUser = `-- name: CountActiveModeratorVouchesForUser :one
SELECT COUNT(*) FROM vouches v
JOIN users u ON u.id = v.voucher_id
WHERE v.vouchee_id = $1
  AND v.status = 'active'
  AND u.role IN ('moderator', 'council')
  AND u.is_active = TRUE
  AND (u.suspended_until IS NULL OR u.suspended_until <= NOW())
`

// The suspension clause pairs with is_active for the reason spelled out at the
// top of users.sql: a suspension is an expiry rather than a flag, so asking
// only `is_active = TRUE` would let a suspended moderator's vouch carry someone
// to promotion, and dropping the pair would keep discounting it long after the
// suspension lapsed.
func (q *Queries) CountActiveModeratorVouchesForUser(ctx context.Context, voucheeID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveModeratorVouchesForUser, voucheeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveVouchesWithAvgTrust = `-- name: CountActiveVouchesWithAvgTrust :one
SELECT COUNT(*) AS vouch_count, COALESCE(AVG(u.trust_score), 0)::double precision AS avg_trust
FROM vouches v
JOIN users u ON u.id = v.voucher_id
WHERE v.vouchee_id = $1 AND v.status = 'active'
`

type CountActiveVouchesWithAvgTrustRow struct {
	VouchCount int64   `json:"vouch_count"`
	AvgTrust   float64 `json:"avg_trust"`
}

func (q *Queries) CountActiveVouchesWithAvgTrust(ctx context.Context, voucheeID string) (CountActiveVouchesWithAvgTrustRow, error) {
	row := q.db.QueryRow(ctx, countActiveVouchesWithAvgTrust, voucheeID)
	var i CountActiveVouchesWithAvgTrustRow
	err := row.Scan(&i.VouchCount, &i.AvgTrust)
	return i, err
}

const countVouchesByVoucherSince = `-- name: CountVouchesByVoucherSince :one
SELECT COUNT(*) FROM vouches
WHERE voucher_id = $1 AND created_at >= $2
`

type CountVouchesByVoucherSinceParams struct {
	VoucherID string             `json:"voucher_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountVouchesByVoucherSince(ctx context.Context, arg CountVouchesByVoucherSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVouchesByVoucherSince, arg.VoucherID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVouch = `-- name: CreateVouch :one
INSERT INTO vouches (id, voucher_id, vouchee_id, status, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, voucher_id, vouchee_id, status, created_at, revoked_at
`

type CreateVouchParams struct {
	ID        string             `json:"id"`
	VoucherID string             `json:"voucher_id"`
	VoucheeID string             `json:"vouchee_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateVouch(ctx context.Context, arg CreateVouchParams) (Vouch, error) {
	row := q.db.QueryRow(ctx, createVouch,
		arg.ID,
		arg.VoucherID,
		arg.VoucheeID,
		arg.Status,
		arg.CreatedAt,
	)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getVouchByID = `-- name: GetVouchByID :one
SELECT id, voucher_id, vouchee_id, status, created_at, revoked_at FROM vouches WHERE id = $1
`

func (q *Queries) GetVouchByID(ctx context.Context, id string) (Vouch, error) {
	row := q.db.QueryRow(ctx, getVouchByID, id)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getVouchByPair = `-- name: GetVouchByPair :one
SELECT id, voucher_id, vouchee_id, status, created_at, revoked_at FROM vouches WHERE voucher_id = $1 AND vouchee_id = $2
`

type GetVouchByPairParams struct {
	VoucherID string `json:"voucher_id"`
	VoucheeID string `json:"vouchee_id"`
}

// Deliberately unfiltered by status. A pair has at most one row —
// UNIQUE(voucher_id, vouchee_id) — so this is the whole history of the pair,
// and the service needs the revoked row as much as the active one: an active
// one is a duplicate to refuse, a revoked one is the row ReactivateVouch
// brings back.
func (q *Queries) GetVouchByPair(ctx context.Context, arg GetVouchByPairParams) (Vouch, error) {
	row := q.db.QueryRow(ctx, getVouchByPair, arg.VoucherID, arg.VoucheeID)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveVouchesByVouchee = `-- name: ListActiveVouchesByVouchee :many
SELECT v.id, v.voucher_id, v.vouchee_id, v.status, v.created_at, v.revoked_at,
       voucher.display_name AS voucher_display_name,
       vouchee.display_name AS vouchee_display_name
FROM vouches v
JOIN users voucher ON voucher.id = v.voucher_id
JOIN users vouchee ON vouchee.id = v.vouchee_id
WHERE v.vouchee_id = $1 AND v.status = 'active'
ORDER BY v.created_at
`

type ListActiveVouchesByVoucheeRow struct {
	Vouch              Vouch  `json:"vouch"`
	VoucherDisplayName string `json:"voucher_display_name"`
	VoucheeDisplayName string `json:"vouchee_display_name"`
}

// Both parties are joined by name because a vouch list is about people, and the
// id alone is unreadable: the profile rendered "0193a7b2..." for every row.
// Inner joins are safe on both sides — voucher_id and vouchee_id are NOT NULL
// references to users — so no row can be dropped by the join. Following the
// feed's convention (posts.sql), the name travels with the row rather than
// being fetched per id afterwards.
func (q *Queries) ListActiveVouchesByVouchee(ctx context.Context, voucheeID string) ([]ListActiveVouchesByVoucheeRow, error) {
	rows, err := q.db.Query(ctx, listActiveVouchesByVouchee, voucheeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveVouchesByVoucheeRow{}
	for rows.Next() {
		var i ListActiveVouchesByVoucheeRow
		if err := rows.Scan(
			&i.Vouch.ID,
			&i.Vouch.VoucherID,
			&i.Vouch.VoucheeID,
			&i.Vouch.Status,
			&i.Vouch.CreatedAt,
			&i.Vouch.RevokedAt,
			&i.VoucherDisplayName,
			&i.VoucheeDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVouchesByVoucher = `-- name: ListActiveVouchesByVoucher :many
SELECT v.id, v.voucher_id, v.vouchee_id, v.status, v.created_at, v.revoked_at,
       voucher.display_name AS voucher_display_name,
       vouchee.display_name AS vouchee_display_name
FROM vouches v
JOIN users voucher ON voucher.id = v.voucher_id
JOIN users vouchee ON vouchee.id = v.vouchee_id
WHERE v.voucher_id = $1 AND v.status = 'active'
ORDER BY v.created_at
`

type ListActiveVouchesByVoucherRow struct {
	Vouch              Vouch  `json:"vouch"`
	VoucherDisplayName string `json:"voucher_display_name"`
	VoucheeDisplayName string `json:"vouchee_display_name"`
}

// The other direction of the same list, joined the same way.
func (q *Queries) ListActiveVouchesByVoucher(ctx context.Context, voucherID string) ([]ListActiveVouchesByVoucherRow, error) {
	rows, err := q.db.Query(ctx, listActiveVouchesByVoucher, voucherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveVouchesByVoucherRow{}
	for rows.Next() {
		var i ListActiveVouchesByVoucherRow
		if err := rows.Scan(
			&i.Vouch.ID,
			&i.Vouch.VoucherID,
			&i.Vouch.VoucheeID,
			&i.Vouch.Status,
			&i.Vouch.CreatedAt,
			&i.Vouch.RevokedAt,
			&i.VoucherDisplayName,
			&i.VoucheeDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateVouch = `-- name: ReactivateVouch :one
UPDATE vouches
SET status = 'active', created_at = $2, revoked_at = NULL
WHERE id = $1 AND status = 'revoked'
RETURNING id, voucher_id, vouchee_id, status, created_at, revoked_at
`

type ReactivateVouchParams struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Vouching again for someone you previously revoked reuses that row rather
// than inserting a second one, because the unique constraint on the pair means
// there can never be a second one to insert.
//
// created_at moves to the new vouch's timestamp so the row reads as the
// endorsement it now is: the daily limit counts from created_at, so leaving it
// at the original date would let a member revoke and re-vouch without ever
// spending an allowance. revoked_at is cleared for the same reason — a
// revocation that has been undone must leave no trace that ListActiveVouches*
// or the trust calculation could still read.
//
// The status guard makes this a no-op on an already-active row, so a caller
// that reached here on a live vouch gets no rows rather than silently
// refreshing somebody's vouch date.
func (q *Queries) ReactivateVouch(ctx context.Context, arg ReactivateVouchParams) (Vouch, error) {
	row := q.db.QueryRow(ctx, reactivateVouch, arg.ID, arg.CreatedAt)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeVouch = `-- name: RevokeVouch :one
UPDATE vouches
SET status = 'revoked', revoked_at = NOW()
WHERE id = $1 AND status = 'active'
RETURNING id, voucher_id, vouchee_id, status, created_at, revoked_at
`

func (q *Queries) RevokeVouch(ctx context.Context, id string) (Vouch, error) {
	row := q.db.QueryRow(ctx, revokeVouch, id)
	var i Vouch
	err := row.Scan(
		&i.ID,
		&i.VoucherID,
		&i.VoucheeID,
		&i.Status,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}
